from datetime import datetime

from mic2md import index
from mic2md.writer import SessionWriter


def _session(root, started, meeting):
    w = SessionWriter(root, started, "en", "base.en", {"meeting": meeting, "participants": ""})
    w.append("hello")
    w.finalize("# Polished", None, started)
    return w.path


def test_sessions_are_stored_by_year_month(tmp_path):
    path = _session(tmp_path, datetime(2026, 9, 23, 20, 5, 7), "")
    assert path.relative_to(tmp_path).as_posix() == "transcripts/2026-09/2026-09-23T20-05-07.md"


def test_index_lists_all_sessions_newest_first_grouped_by_month(tmp_path):
    _session(tmp_path, datetime(2026, 8, 31, 9, 0, 0), "Retro | August")
    _session(tmp_path, datetime(2026, 9, 23, 20, 5, 7), "Sprint planning")
    _session(tmp_path, datetime(2026, 9, 24, 8, 30, 0), "")
    (tmp_path / "transcripts" / "notes.md").write_text("not a session")

    text = index.update(tmp_path).read_text()

    assert text.index("## 2026-09") < text.index("## 2026-08")
    assert text.index("2026-09-24") < text.index("2026-09-23")
    assert (
        "| [2026-09-23](transcripts/2026-09/2026-09-23T20-05-07.md) | 20:05 | Sprint planning |"
        in text
    )
    assert "| 08:30 |  |" in text
    assert "Retro \\| August" in text
    assert "notes.md" not in text


def test_empty_index(tmp_path):
    assert "No transcripts yet." in index.update(tmp_path).read_text()


def test_migrate_flat_moves_old_sessions(tmp_path):
    old = tmp_path / "2026-09-23T20-26-07.md"
    old.write_text("---\ndate: 2026-09-23T20:26:07+02:00\nmeeting: Old\n---\n\nhi\n")
    (tmp_path / "README.md").write_text("keep me")

    moved = index.migrate_flat(tmp_path)

    assert moved == [tmp_path / "transcripts/2026-09/2026-09-23T20-26-07.md"]
    assert not old.exists() and (tmp_path / "README.md").exists()
    assert "| 20:26 | Old |" in index.update(tmp_path).read_text()


def test_tags_round_trip_and_known_tags_most_used_first(tmp_path):
    from mic2md.writer import format_tags, parse_tags

    assert format_tags(["a", "b-c"]) == "[a, b-c]"
    assert parse_tags("[a, b-c]") == ["a", "b-c"]
    assert parse_tags("") == [] and format_tags([]) == ""

    for i, tags in enumerate((["budget", "hiring"], ["budget"], ["roadmap"])):
        w = SessionWriter(
            tmp_path, datetime(2026, 9, 20 + i, 9), "en", "base.en", {"tags": format_tags(tags)}
        )
        w.append("hi")
        w.finalize(None, None, datetime(2026, 9, 20 + i, 10))
    assert index.known_tags(tmp_path)[0] == "budget"
    assert set(index.known_tags(tmp_path)) == {"budget", "hiring", "roadmap"}


def test_index_has_tag_section_and_repo_footer(tmp_path):
    from mic2md import REPO_URL
    from mic2md.writer import format_tags

    for day, meeting, tags in (
        (20, "Budget sync", ["q4-budget"]),
        (27, "", ["q4-budget", "hiring"]),
    ):
        extra = {"meeting": meeting, "tags": format_tags(tags)}
        w = SessionWriter(tmp_path, datetime(2026, 9, day, 9), "en", "base.en", extra)
        w.append("hi")
        w.finalize(None, None, datetime(2026, 9, day, 10))

    text = index.update(tmp_path).read_text()

    tags = text[text.index("## Tags") :]
    assert tags.index("`hiring` (1)") < tags.index("`q4-budget` (2)")
    assert (
        "- `q4-budget` (2): [2026-09-27 09:00](transcripts/2026-09/2026-09-27T09-00-00.md), "
        "[2026-09-20 09:00 Budget sync](transcripts/2026-09/2026-09-20T09-00-00.md)"
    ) in tags
    assert text.rstrip().splitlines()[-1].startswith(f"Generated by [mic2md]({REPO_URL})")


def test_index_without_tags_has_no_tag_section(tmp_path):
    _session(tmp_path, datetime(2026, 9, 23, 20, 5, 7), "x")
    text = index.update(tmp_path).read_text()
    assert "## Tags" not in text and "Generated by [mic2md]" in text
