"""index.md in the output folder: a table of every session, built from their front matter."""

from __future__ import annotations

import re
from collections import Counter
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

from mic2md import REPO_URL
from mic2md.writer import TRANSCRIPTS_DIR, parse_document, parse_tags, session_path

INDEX_FILE = "index.md"
_SESSION_NAME = re.compile(r"\A\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}\.md\Z")


@dataclass
class Entry:
    started: datetime
    meeting: str
    path: Path  # relative to the output folder
    tags: list[str] = field(default_factory=list)


def _started(meta: dict[str, str], path: Path) -> datetime:
    try:
        return datetime.fromisoformat(meta["date"])
    except (KeyError, ValueError):
        return datetime.strptime(path.stem, "%Y-%m-%dT%H-%M-%S")


def collect(output_dir: Path) -> list[Entry]:
    """All session files under ``transcripts/``, newest first."""
    entries = []
    for path in (output_dir / TRANSCRIPTS_DIR).rglob("*.md"):
        if not _SESSION_NAME.match(path.name):
            continue
        # Only the front matter is needed; it sits at the top of the file.
        with path.open(encoding="utf-8") as fh:
            head = fh.read(4096)
        meta, _ = parse_document(head)
        try:
            started = _started(meta, path)
        except ValueError:
            continue
        entries.append(
            Entry(
                started,
                meta.get("meeting", ""),
                path.relative_to(output_dir),
                parse_tags(meta.get("tags", "")),
            )
        )
    entries.sort(key=lambda e: e.started.replace(tzinfo=None), reverse=True)
    return entries


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def _link_text(text: str) -> str:
    return text.replace("[", "\\[").replace("]", "\\]")


def _tag_section(entries: list[Entry]) -> list[str]:
    """``- `tag` — [date meeting](path), …`` for every tag, alphabetically; newest note first."""
    by_tag: dict[str, list[Entry]] = {}
    for e in entries:
        for t in e.tags:
            by_tag.setdefault(t, []).append(e)
    if not by_tag:
        return []
    lines = ["", "## Tags", ""]
    for t in sorted(by_tag):
        links = []
        for e in by_tag[t]:
            label = f"{e.started:%Y-%m-%d %H:%M}" + (f" {e.meeting}" if e.meeting else "")
            links.append(f"[{_link_text(label)}]({e.path.as_posix()})")
        lines.append(f"- `{t}` ({len(links)}): " + ", ".join(links))
    return lines


def render(entries: list[Entry]) -> str:
    lines = ["# Transcripts"]
    if not entries:
        lines += ["", "No transcripts yet."]
    month = None
    for e in entries:
        if (m := f"{e.started:%Y-%m}") != month:
            month = m
            lines += [
                "",
                f"## {month}",
                "",
                "| Date | Time | Meeting | Tags |",
                "|---|---|---|---|",
            ]
        link = f"[{e.started:%Y-%m-%d}]({e.path.as_posix()})"
        tags = " ".join(f"`{t}`" for t in e.tags)
        lines.append(f"| {link} | {e.started:%H:%M} | {_cell(e.meeting)} | {_cell(tags)} |")
    lines += _tag_section(entries)
    lines += [
        "",
        "---",
        "",
        f"Generated by [mic2md]({REPO_URL}). Rebuilt from the notes' front matter after every "
        "recording (or with `mic2md reindex`), so edits to this file are overwritten.",
    ]
    return "\n".join(lines).strip() + "\n"


def known_tags(output_dir: Path, limit: int = 150) -> list[str]:
    """Tags already used in the output folder, most used first (fed to the tagger)."""
    counts = Counter(t for e in collect(output_dir) for t in e.tags)
    return [t for t, _ in counts.most_common(limit)]


def update(output_dir: Path) -> Path:
    """Rebuild ``index.md`` from every session file and write it atomically."""
    path = output_dir / INDEX_FILE
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(render(collect(output_dir)), encoding="utf-8")
    tmp.replace(path)
    return path


def migrate_flat(output_dir: Path) -> list[Path]:
    """Move session files saved directly in the output folder (older versions) into place."""
    moved = []
    for path in sorted(output_dir.glob("*.md")):
        if not _SESSION_NAME.match(path.name):
            continue
        started = datetime.strptime(path.stem, "%Y-%m-%dT%H-%M-%S")
        target = session_path(output_dir, started)
        if target.exists():
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        path.replace(target)
        moved.append(target)
    return moved
